swagger: '2.0'
info:
  version: 0.0.1
  title: Vertigo API
  description: Vertigo API - all best practice in one API
  contact:
    name: Pavel Murkin
    email: kot_tdf@mail.ru
  license:
    name: MIT
host: 'localhost:8000'
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  token_header:
    type: apiKey
    name: X-Api-Key
    in: header
paths:
  /advert:
    get:
      summary: Lists the adverts
      description: Get adverts
      parameters:
        - in: query
          name: query
          required: true
          type: string
        - name: status
          description: the status to filter by
          in: query
          type: array
          uniqueItems: true
          collectionFormat: pipes
          items:
            type: string
            enum:
              - active
              - disable
              - deleted
        - $ref: '#/parameters/pageSize'
        - $ref: '#/parameters/pageNumber'
      responses:
        '200':
          description: Get adverts result
          schema:
            title: AdvertList
            type: array
            items:
              $ref: '#/definitions/AdvertCard'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ValidationError'
parameters:
  pageSize:
    name: pageSize
    type: integer
    format: int32
    in: query
    description: Amount of items to return in a single page
    default: 20
  pageNumber:
    name: pageNumber
    type: integer
    format: int32
    in: query
    description: Number of page
    default: 0
definitions:
  Error:
    title: Error Structure
    description: |
      Contains all the properties any error response from the API will contain.
      Some properties are optional so might be empty most of the time
    type: object
    required:
      - code
      - message
    properties:
      code:
        description: 'the error code, this is not necessarily the http status code'
        type: integer
        format: int32
      message:
        description: a human readable version of the error
        type: string
  ValidationError:
    allOf:
      - $ref: '#/definitions/Error'
      - type: object
        properties:
          field:
            description: an optional field name to which this validation error applies
            type: string
  AdvertCard:
    title: A card for at advert
    type: object
    properties:
      advertId:
        type: integer
      title:
        title: The title of the advert.
        description: |
          The title for a advert, this needs to be at least 5 chars long.
          Titles don't allow any formatting, besides emoji.
        type: string
        minLength: 5
        maxLength: 150
      price:
        title: The price of the advert.
        type: integer
        format: int32
        minimum: 1
        maximum: 100000000
      status:
        title: the status of the issue
        description: |
          There are 3 possible values for a status.
          Ignored means as much as accepted but not now, perhaps later.
        type: string
        enum:
          - active
          - disable
          - deleted
