swagger: '2.0'
info:
  version: 0.0.1
  title: Vertigo API
  description: Vertigo API - all best practice in one API
  contact:
    name: Pavel Murkin
    email: kot_tdf@mail.ru
  license:
    name: MIT
host: 'localhost:8000'
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: advert
    description: Everything about Advert
  - name: support
    description: Everything for support
securityDefinitions:
  token_header:
    type: apiKey
    name: X-Api-Key
    in: header
paths:
  /advert:
    get:
      tags:
        - advert
      summary: Lists the adverts
      description: Get adverts
      parameters:
        - name: status
          description: Advert status
          in: query
          type: array
          uniqueItems: true
          collectionFormat: pipes
          items:
            type: string
            enum:
              - active
              - disabled
              - deleted

        - name: price
          description: 'Price of good: [min, max]'
          in: query
          type: array
          items:
            type: integer
            format: int32

        - name: pageSize
          type: integer
          format: int32
          in: query
          description: Amount of items to return in a single page
          default: 20
          minimum: 0
          maximum: 100

        - name: pageNumber
          type: integer
          format: int32
          in: query
          description: Number of page
          default: 0
          minimum: 0
      responses:
        '200':
          description: Get adverts result
          schema:
            title: AdvertList
            type: array
            items:
              $ref: './advert.yml'
        '400':
          description: Validation error
          schema:
            $ref: '#/definitions/ValidationError'
    post:
      tags:
        - advert
      summary: Create new advert
      description: Create new advert
      parameters:
        - name: body
          in: body
          description: The advert to create
          required: true
          schema:
            $ref: './advert.yml'
      responses:
        '200':
          description: Advert
          schema:
            $ref: './advert.yml'

  /advert/{id}:
    parameters:
      - name: id
        description: The id of the advert
        type: integer
        format: int64
        in: path
        required: true
    get:
      tags:
        - advert
      summary: Advert
      description: Get advert
      responses:
        '200':
          description: Advert
          schema:
            $ref: './advert.yml'
        '404':
          description: Advert not found
          schema:
            $ref: '#/definitions/AdvertNotFound'

    patch:
      tags:
        - advert
      summary: Update advert
      description: Update advert
      parameters:
        - name: body
          in: body
          description: The advert to update
          required: true
          schema:
            $ref: './advert.yml'
      responses:
        '200':
          description: Advert
          schema:
            $ref: './advert.yml'
        '404':
          description: Advert not found
          schema:
            $ref: '#/definitions/AdvertNotFound'

    delete:
      tags:
        - advert
      summary: Delete advert
      description: Delete advert
      responses:
        '204':
          description: Advert is deleted

        '404':
          description: Advert not found
          schema:
            $ref: '#/definitions/AdvertNotFound'

  /health-check:
    get:
      tags:
        - support
      summary: Health check
      description: Health check
      responses:
        '200':
          description: Get health check info
          schema:
            $ref: '#/definitions/HealthCheck'

definitions:
  Error:
    title: Error Structure
    description: |
      Contains all the properties any error response from the API will contain.
      Some properties are optional so might be empty most of the time
    type: object
    required:
      - code
      - message
    properties:
      code:
        description: 'the error code, this is not necessarily the http status code'
        type: integer
        format: int32
      message:
        description: a human readable version of the error
        type: string

  ValidationError:
    allOf:
      - $ref: '#/definitions/Error'
      - type: object
        properties:
          field:
            description: an optional field name to which this validation error applies
            type: string

  AdvertNotFound:
    allOf:
      - $ref: '#/definitions/Error'
      - type: object
        properties:
          field:
            description: an optional field name to which this validation error applies
            type: string

  HealthCheck:
    title: HealthCheck
    type: object
    properties:
      status:
        title: Status of work service
        type: string
        enum:
          - ok
          - fail
      buildTime:
        title: BuildTime is a time label of the moment when the binary was built
        type: string
      commit:
        title: Commit is a last commit hash at the moment when the binary was built
        type: string
      release:
        title: Release is a semantic version of current build
        type: string
      branch:
        title: Branch is a branch from which the binary was built
        type: string
